version: '3'
services:
  node-express-docker:
    environment:
      - NODE_ENV=production
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/app
    container_name: node-express-docker
    expose:
      - "8080" 
    ports:
      - "8080:8080"
    command: npm run build