AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Subnet1ID:
    Type: String
  Subnet2ID:
    Type: String
  VPCID:
    Type: String
  DomainName:
    Type: String
Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      # rename after first deploy
      ServiceName: aws-ecs-firegate-service-main
      Cluster: arn:aws:ecs:us-east-2:452158465117:cluster/aws-ecs-firegate-api
      TaskDefinition: arn:aws:ecs:us-east-2:452158465117:task-definition/aws-ecs-firegate-task:45
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet1ID
            - !Ref Subnet2ID
          SecurityGroups:
            - sg-079fa5dec06026d7c
      LoadBalancers:
        - TargetGroupArn: arn:aws:elasticloadbalancing:us-east-2:452158465117:targetgroup/aws-ecs-firegate-tg/4f59b86262feff88
          ContainerPort: 8080
          ContainerName: aws-ecs-firegate-container

# aws cloudformation update-stack --stack-name aws-ecs-firegate-api --template-body file://./ecs-2.yml --capabilities CAPABILITY_NAMED_IAM \
# --parameters ParameterKey=VPCID,ParameterValue=YOUR_VPC_ID \
# ParameterKey=Subnet1ID,ParameterValue=YOUR_SUBNET_1_ID \
# ParameterKey=Subnet2ID,ParameterValue=YOUR_SUBNET_2_ID \
# ParameterKey=DomainName,ParameterValue=YOUR_DOMAIN_NAME.com
